apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-tutorial
  template:
    metadata:
      labels:
        app: react-tutorial
    spec:
      containers:
      - name: react-tutorial-frontend
        image: brunokrebs/react-tutorial
#        uncomment if you need to refresh image on k8s
#        imagePullPolicy: Always
        ports:
          - name: http-react
            containerPort: 3001
